// ./utils/timestampMappingWink.ts
import { WinkMethods, ItemToken } from 'wink-nlp';
import bm25Vectorizer from 'wink-nlp/utilities/bm25-vectorizer';
import { TranscriptResponse } from './fetchTranscript'; // Adjust path if needed
import similarity from 'wink-nlp/utilities/similarity';

// Re-define TimedChunk here or import if defined globally
export interface TimedChunk {
  text: string;
  startOffset: number;
  endOffset: number;
}

/**
 * Helper function to get the first N words (tokens) using wink-nlp tokenizer.
 */
function getFirstNWordsWink(text: string, n: number, nlp: WinkMethods): string {
  if (!text || n <= 0) return '';
  const doc = nlp.readDoc(text);
  // Filter out punctuation/spaces if needed, depending on desired 'word' count
  const tokens = doc.tokens().filter((t: ItemToken) => t.out(nlp.its.type) === 'word');
  return tokens.out().slice(0, n).join(' '); // Get text of first N words
}

/**
 * Maps fine-grained text chunks to original transcript timestamps using wink-nlp's
 * BM25 vectorization and similarity.
 *
 * @param originalSegments Raw transcript segments with offsets and durations.
 * @param fineTextChunks Array of text chunks generated by the fine-chunking agent.
 * @param nlp An initialized instance of winkNLP.
 * @param config Configuration options.
 * @param config.wordsToMatch Number of words from the start of segments/chunks to use for matching. Default: 50.
 * @param config.similarityThreshold Minimum BM25 similarity score required for a match. Needs tuning. Default: 0.01.
 * @returns An array of TimedChunk objects.
 */
export function mapFineChunksToTimestampsWink(
  originalSegments: TranscriptResponse[],
  fineTextChunks: string[],
  nlp: WinkMethods,
  config?: {
    wordsToMatch?: number;
    similarityThreshold?: number;
  }
): TimedChunk[] {

  const {
    wordsToMatch = 50,
    similarityThreshold = 0.01 // BM25 scores are different from cosine sim, start very low!
  } = config || {};

  console.log(`[mapFineChunksWink] Starting mapping. Words: ${wordsToMatch}, Threshold: ${similarityThreshold}`);

  const timedChunks: TimedChunk[] = [];

  // --- Input Validation ---
  if (!originalSegments || originalSegments.length === 0) {
    console.error('[mapFineChunksWink] Error: Original transcript segments are missing or empty.');
    return []; // Return empty, don't throw to allow workflow continuation maybe? Or throw?
  }
  if (!fineTextChunks || fineTextChunks.length === 0) {
    console.warn('[mapFineChunksWink] No fine text chunks provided. Returning empty array.');
    return [];
  }
  if (!nlp) {
    console.error('[mapFineChunksWink] Error: winkNLP instance not provided.');
    return []; // Or throw
  }

  try {
    // --- Preprocessing ---
    console.log(`[mapFineChunksWink] Preparing snippets for ${originalSegments.length} segments and ${fineTextChunks.length} chunks...`);
    const segmentSnippets = originalSegments.map((segment, index) => ({
      id: `seg_${index}`, // Unique ID for each segment
      text: getFirstNWordsWink(segment.text || '', wordsToMatch, nlp)
    }));

    const chunkSnippets = fineTextChunks.map((chunk, index) => ({
      id: `chunk_${index}`, // Unique ID for each chunk snippet
      text: getFirstNWordsWink(chunk || '', wordsToMatch, nlp)
    }));

    // Filter out segments with empty snippets (can happen with very short segments)
    const validSegmentSnippets = segmentSnippets.filter(s => s.text.trim().length > 0);
    if (validSegmentSnippets.length !== segmentSnippets.length) {
      console.warn(`[mapFineChunksWink] Filtered out ${segmentSnippets.length - validSegmentSnippets.length} original segments due to empty snippets after truncation.`);
    }
    if (validSegmentSnippets.length === 0) {
      console.error('[mapFineChunksWink] Error: No valid segment snippets found after preprocessing.');
      return [];
    }


    // --- BM25 Vectorization & Similarity ---
    console.log(`[mapFineChunksWink] Training BM25 model on ${validSegmentSnippets.length} segment snippets...`);
    const bm25 = bm25Vectorizer();
    // Train the model using the segment snippets
    bm25.learn(validSegmentSnippets.map(s => s.text));

    console.log(`[mapFineChunksWink] Calculating similarities for ${chunkSnippets.length} chunks...`);
    for (let i = 0; i < chunkSnippets.length; i++) {
      const chunkSnippet = chunkSnippets[i];
      const originalChunkText = fineTextChunks[i]; // Keep the full original text

      if (!chunkSnippet.text || chunkSnippet.text.trim().length === 0) {
        console.warn(`[mapFineChunksWink] Skipping chunk index ${i} due to empty snippet after truncation. Original Text: "${getFirstNWordsWink(originalChunkText, 10, nlp)}..."`);
        continue;
      }
      if (!originalChunkText || originalChunkText.trim().length === 0) {
        console.warn(`[mapFineChunksWink] Skipping empty original chunk text at index ${i}.`);
        continue;
      }

      // Find similarity scores between the chunk snippet and all learned segment snippets.
      const similarityScores = validSegmentSnippets.map((segment, idx) => {
        // Simple word overlap score
        const chunkWords = new Set(chunkSnippet.text.toLowerCase().split(/\s+/));
        const segmentWords = new Set(segment.text.toLowerCase().split(/\s+/));
        const intersection = new Set([...chunkWords].filter(x => segmentWords.has(x)));
        const score = intersection.size / Math.max(chunkWords.size, segmentWords.size);
        return [score, idx];
      }).sort((a, b) => b[0] - a[0]); // Sort by similarity score descending

      // --- DEBUG LOGGING --- START
      // console.log(`[mapFineChunksWink] DEBUG: Similarity results for chunk ${i}:`, JSON.stringify(similarityScores));
      // if (similarityScores && similarityScores.length > 0) {
      //   console.log(`[mapFineChunksWink] DEBUG: similarityScores[0] for chunk ${i}:`, JSON.stringify(similarityScores[0]));
      // } else {
      //   console.log(`[mapFineChunksWink] DEBUG: Similarity array is empty or null for chunk ${i}.`);
      // }
      // --- DEBUG LOGGING --- END

      if (!similarityScores || similarityScores.length === 0) {
        console.warn(`[mapFineChunksWink] BM25 returned no similarity scores for chunk ${i}. Text: "${chunkSnippet.text.substring(0, 30)}..."`);
        continue;
      }

      // The first element has the highest score
      // similarityScores[0] is [score, learnedDocIndex]
      const [bestScore, bestMatchLearnedIndex] = similarityScores[0];

      // Need to map bestMatchLearnedIndex (index within the *learned* corpus - validSegmentSnippets)
      // back to the index in the *original* originalSegments array.
      const matchedSnippetData = validSegmentSnippets[bestMatchLearnedIndex];
      const originalSegmentIndexMatch = segmentSnippets.findIndex(s => s.id === matchedSnippetData.id);


      // --- Timestamp Assignment (Option A) ---
      if (originalSegmentIndexMatch !== -1 && bestScore >= similarityThreshold) {
        const matchedSegment = originalSegments[originalSegmentIndexMatch];

        // Basic sanity check for timestamps
        const startOffset = matchedSegment.offset; // Assume offset is already in seconds
        const endOffset = matchedSegment.offset + matchedSegment.duration; // Assume duration is already in seconds

        if (typeof startOffset !== 'number' || Number.isNaN(startOffset) || typeof endOffset !== 'number' || Number.isNaN(endOffset) || endOffset < startOffset) {
          console.warn(`[mapFineChunksWink] Invalid timestamps found for matched segment index ${originalSegmentIndexMatch}. Start: ${startOffset}, End: ${endOffset}. Skipping chunk ${i}.`);
          continue;
        }


        timedChunks.push({
          text: originalChunkText, // Use the original full chunk text
          startOffset: parseFloat(startOffset.toFixed(3)),
          endOffset: parseFloat(endOffset.toFixed(3)),
        });
        // Optional: Log success
        // console.log(`[mapFineChunksWink] Chunk ${i} matched original segment ${originalSegmentIndexMatch} (BM25 Score: ${bestScore.toFixed(4)}) -> [${startOffset.toFixed(3)} - ${endOffset.toFixed(3)}]`);

      } else {
        // Log failure reason
        const reason = originalSegmentIndexMatch === -1 ? `Could not map learned index ${bestMatchLearnedIndex} back to original segment.`
          : `Similarity score ${bestScore.toFixed(4)} is below threshold ${similarityThreshold}.`;
        console.warn(
          `[mapFineChunksWink] Could not map chunk ${i}. ${reason} Text: "${chunkSnippet.text.substring(0, 30)}..."`
        );
      }
    }

  } catch (error) {
    console.error('[mapFineChunksWink] Unexpected error during timestamp mapping:', error);
    // Decide whether to return partial results or throw
    // return []; // Return empty on error
    throw error; // Or re-throw
  }

  console.log(`[mapFineChunksWink] Finished mapping. Created ${timedChunks.length} timed chunks from ${fineTextChunks.length} inputs.`);
  return timedChunks;
}