import Fuse from 'fuse.js';
import { TranscriptResponse } from './fetchTranscript';

/**
 * Represents a text chunk with associated start and end timestamps (in seconds).
 */
export interface TimedChunk {
  text: string;
  startOffset: number;
  endOffset: number;
}

/**
 * Helper function to find the original segment(s) corresponding to character indices
 * within the formatted transcript text (the text processed by `formatTranscript`).
 *
 * @param startIndex The starting character index of the match in formattedTranscriptText.
 * @param endIndex The ending character index (exclusive) of the match in formattedTranscriptText.
 * @param formattedTranscriptText The exact text string generated by formatTranscript.
 * @param originalSegments The raw transcript segments with original timestamps.
 * @returns An object containing the start and end segment info, or null if mapping fails.
 */
function mapFormattedIndicesToSegments(
  startIndex: number,
  endIndex: number,
  formattedTranscriptText: string, // Keep for potential future validation if needed
  originalSegments: TranscriptResponse[],
): { startSegment: TranscriptResponse; endSegment: TranscriptResponse } | null {
  if (!originalSegments || originalSegments.length === 0) {
    return null;
  }

  let cumulativeFormattedLength = 0;
  let startSegmentIndex = -1;
  let endSegmentIndex = -1;

  for (let i = 0; i < originalSegments.length; i++) {
    const segment = originalSegments[i];
    // Replicate the formatting logic: trim and add space length (except for first segment)
    const segmentFormattedText = segment.text ? segment.text.trim() : '';
    const segmentFormattedLength = segmentFormattedText.length;
    const separatorLength = i > 0 ? 1 : 0; // Length of the space separator

    const currentSegmentEndIndex =
      cumulativeFormattedLength + separatorLength + segmentFormattedLength;

    // Check if the match starts within this segment (or its preceding space)
    if (startSegmentIndex === -1 && startIndex < currentSegmentEndIndex) {
      startSegmentIndex = i;
    }

    // Check if the match ends within this segment (or its preceding space)
    // endIndex is exclusive, so we check if it's <= the end boundary
    if (endSegmentIndex === -1 && endIndex <= currentSegmentEndIndex) {
      endSegmentIndex = i;
    }

    // Optimization: if we've found both, break the loop
    if (startSegmentIndex !== -1 && endSegmentIndex !== -1) {
      break;
    }

    cumulativeFormattedLength = currentSegmentEndIndex;
  }

  // Handle edge case where match extends to the very end
  if (
    startSegmentIndex !== -1 &&
    endSegmentIndex === -1 &&
    endIndex === formattedTranscriptText.length
  ) {
    endSegmentIndex = originalSegments.length - 1;
  }

  if (startSegmentIndex !== -1 && endSegmentIndex !== -1) {
    return {
      startSegment: originalSegments[startSegmentIndex],
      endSegment: originalSegments[endSegmentIndex],
    };
  } 
  // If the loop finished without finding both indices (or handling the edge case)
  console.warn(
    `Failed to map formatted indices [${startIndex}-${endIndex}] to original segments. Start found: ${startSegmentIndex}, End found: ${endSegmentIndex}`,
  );
  return null;
}

/**
 * Maps semantically chunked text (from an LLM) back to the original transcript timestamps
 * using Fuse.js for fuzzy matching.
 *
 * @param originalSegments The raw transcript segments with original timestamps.
 * @param fineTextChunks The array of text chunks generated by the fine-chunking agent.
 * @param formattedTranscriptText The exact text string that was sent to the fine-chunking agent.
 * @returns An array of TimedChunk objects with calculated start and end offsets.
 */
export function mapFineChunksToTimestamps(
  originalSegments: TranscriptResponse[],
  fineTextChunks: string[],
  formattedTranscriptText: string,
): TimedChunk[] {
  const timedChunks: TimedChunk[] = [];

  if (
    !originalSegments ||
    originalSegments.length === 0 ||
    !fineTextChunks ||
    fineTextChunks.length === 0 ||
    !formattedTranscriptText
  ) {
    console.warn(
      'Cannot map timestamps: Empty original segments, fine text chunks, or formatted transcript provided.',
    );
    return timedChunks;
  }

  // Configure Fuse.js
  const fuseOptions = {
    includeScore: true,
    includeMatches: true, // Necessary to get indices
    threshold: 0.7, // <-- Increased threshold again
    minMatchCharLength: 5, // Ignore very short matches
  };

  // We search within the *exact* formatted text that was sent to the LLM
  // Fuse expects an array to search within.
  const fuse = new Fuse([formattedTranscriptText], fuseOptions);

  for (const chunkText of fineTextChunks) {
    if (!chunkText || chunkText.trim().length === 0) {
      console.warn('Skipping empty chunk text.');
      continue;
    }

    const results = fuse.search(chunkText);

    if (results.length === 0) {
      console.warn(
        `Fuse.js could not find match for chunk: "${chunkText.substring(
          0,
          70,
        )}..."`,
      );
      continue;
    }

    // Use the best match (results[0])
    const bestMatch = results[0];

    // Explicitly check for matches, as it's optional in the type definition
    if (!bestMatch.matches || bestMatch.matches.length === 0) {
       console.warn(
        `Fuse.js found a result but no match indices for chunk: "${chunkText.substring(
          0,
          70,
        )}..."`,
      );
       continue;
    }

    // Fuse provides match indices as [start, end] inclusive.
    // We need the overall start of the first matched part and end of the last matched part.
    // Since we searched an array of one string, matches[0] corresponds to that string.
    const matchIndices = bestMatch.matches[0].indices; 
    if (!matchIndices || matchIndices.length === 0) {
       console.warn(
        `Fuse.js found a result but missing indices array for chunk: "${chunkText.substring(
          0,
          70,
        )}..."`,
      );
        continue;
    }
    const matchStartIndex = matchIndices[0][0]; // Start of the first tuple
    const matchEndIndex = matchIndices[matchIndices.length - 1][1] + 1; // End of the last tuple + 1 (exclusive)

    // Now map these indices (from formattedTranscriptText) back to original segments
    const segmentInfo = mapFormattedIndicesToSegments(
      matchStartIndex,
      matchEndIndex,
      formattedTranscriptText,
      originalSegments,
    );

    if (segmentInfo) {
      const startOffset = segmentInfo.startSegment.offset;
      // Use the end time of the *last* segment the match touched
      const endOffset =
        segmentInfo.endSegment.offset + segmentInfo.endSegment.duration;

      timedChunks.push({
        text: chunkText, // Keep the LLM's version of the text
        startOffset,
        endOffset,
      });
    } else {
      // mapFormattedIndicesToSegments already logged a warning
    }
  }

  if (
    timedChunks.length !== fineTextChunks.length &&
    fineTextChunks.length > 0
  ) {
    console.warn(
      `Timestamp mapping mismatch: Input chunks: ${fineTextChunks.length}, Mapped chunks: ${timedChunks.length}. Some chunks could not be mapped.`,
    );
  }

  return timedChunks;
} 